hl.config({ decoration = { rounding = 21 } })
hl.config({ decoration = { blur = { enabled = true } } })
hl.config({ decoration = { blur = { size = 2 } } })
hl.config({ decoration = { blur = { passes = 3 } } })
hl.config({ decoration = { active_opacity = 1 } })
hl.config({ decoration = { inactive_opacity = 0.9 } })
hl.config({ general = { border_size = 1 } })
hl.config({ general = { gaps_in = 2 } })
hl.config({ general = { gaps_out = 5 } })
hl.config({ general = { layout = "dwindle" } })
hl.config({ animations = { enabled = true } })
hl.config({ input = { kb_layout = "us" } })
hl.config({ input = { numlock_by_default = true } })
hl.config({ input = { repeat_delay = 250 } })
hl.config({ input = { repeat_rate = 35 } })
hl.config({ input = { follow_mouse = 0 } })
hl.config({ input = { touchpad = { natural_scroll = true } } })
hl.config({ input = { touchpad = { disable_while_typing = true } } })
hl.config({ input = { touchpad = { clickfinger_behavior = false } } })
hl.config({ input = { touchpad = { scroll_factor = 0.7 } } })
hl.config({ decoration = { screen_shader = "/home/upicy/.config/quickshell/end4-pC/services/hyprlandAntiFlashbangShader/anti-flashbang.glsl" } })
hl.config({ debug = { damage_tracking = 1 } })
