# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(141312)
$foreground = rgb(EEE1D2)
$color0 = rgb(3B3B39)
$color1 = rgb(151009)
$color2 = rgb(1F1610)
$color3 = rgb(432317)
$color4 = rgb(592D1F)
$color5 = rgb(592D1F)
$color6 = rgb(9A7F5F)
$color7 = rgb(DECCB7)
$color8 = rgb(9B8E80)
$color9 = rgb(1C160C)
$color10 = rgb(2A1E16)
$color11 = rgb(592F1F)
$color12 = rgb(773C29)
$color13 = rgb(773C29)
$color14 = rgb(CEA97F)
$color15 = rgb(DECCB7)
