#!/bin/bash
COLORS_DIR="$HOME/.config/rice-themes/color-schemes"
KITTY_THEMES="$HOME/.config/kitty/kitty-themes"
SELECTED=$(ls "$COLORS_DIR" | sed 's/\.css$//' | rofi -dmenu -p "Color Scheme" -theme ~/.config/rofi/launcher.rasi)
[[ -z "$SELECTED" ]] && exit 0

ln -sf "$COLORS_DIR/$SELECTED.css" "$HOME/.config/waybar/colors.css"

# Parse the CSS variables so kitty uses the exact same colors (always readable)
get() { grep -E "^@define-color $1 " "$COLORS_DIR/$SELECTED.css" | awk '{print $3}' | tr -d ';'; }
base=$(get base)
mantle=$(get mantle)
crust=$(get crust)
text=$(get text)
subtext=$(get subtext)
overlay=$(get overlay)
accent=$(get accent)
accent2=$(get accent2)
green=$(get green)
yellow=$(get yellow)
orange=$(get orange)
red=$(get red)

KITTY_COLORS="$KITTY_THEMES/02-Scheme.conf"
{
  echo "# Generated by color-scheme-picker.sh ($SELECTED)"
  echo "foreground         $text"
  echo "background         $base"
  echo "cursor            $accent"
  echo ""
  echo "active_tab_foreground     $base"
  echo "active_tab_background     $text"
  echo "inactive_tab_foreground   $text"
  echo "inactive_tab_background   $mantle"
  echo ""
  echo "active_border_color   $accent"
  echo "inactive_border_color $overlay"
  echo "bell_border_color     $red"
  echo ""
  echo "color0      $base"
  echo "color1      $red"
  echo "color2      $green"
  echo "color3      $yellow"
  echo "color4      $accent2"
  echo "color5      $accent"
  echo "color6      $orange"
  echo "color7      $subtext"
  echo "color8      $overlay"
  echo "color9      $red"
  echo "color10     $green"
  echo "color11     $yellow"
  echo "color12     $accent2"
  echo "color13     $accent"
  echo "color14     $orange"
  echo "color15     $text"
} > "$KITTY_COLORS"

# Ensure kitty includes the scheme override (after wallpaper colors, so user choice wins)
if ! grep -q "02-Scheme.conf" "$KITTY_THEMES/00-Default.conf"; then
  echo "include ./02-Scheme.conf" >> "$KITTY_THEMES/00-Default.conf"
fi

# Reload kitty (SIGUSR1 makes kitty reload config without losing session)
if pidof kitty >/dev/null; then
  for pid in $(pidof kitty); do kill -SIGUSR1 "$pid" 2>/dev/null || true; done
else
  nohup kitty > /dev/null 2>&1 & disown
fi

pkill waybar; nohup waybar > /dev/null 2>&1 & disown
notify-send "Colors" "Scheme applied: $SELECTED"
