# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EEE1D2
background         #141312
cursor             #8C7F74

active_tab_foreground     #141312
active_tab_background     #EEE1D2
inactive_tab_foreground   #EEE1D2
inactive_tab_background   #141312

active_border_color   #EEE1D2
inactive_border_color #141312
bell_border_color     #151009

color0      #3B3B39
color1		#151009
color2		#1F1610
color3		#432317
color4		#592D1F
color5		#592D1F
color6		#9A7F5F
color7		#DECCB7
color8		#9B8E80
color9		#1C160C
color10		#2A1E16
color11		#592F1F
color12		#773C29
color13		#773C29
color14		#CEA97F
color15		#DECCB7
